#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

"G:\Program Files\nodejs\node.exe"  "$basedir/../../AppData/Roaming/npm/pnpm-global/5/node_modules/pnpm/bin/pnpm.cjs" "$@"
exit $?
